"""agregar pagos

Revision ID: f59480d6e431
Revises: f7f20cb5f061
Create Date: 2025-12-06 17:13:01.372533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f59480d6e431'
down_revision: Union[str, Sequence[str], None] = 'f7f20cb5f061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('periodo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    # ### end Alembic commands ###
