"""empty message

Revision ID: f7127eb1936d
Revises: 
Create Date: 2025-12-06 16:31:21.756413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f7127eb1936d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquilino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dni', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propietario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dni', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inmueble',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('altura', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('barrio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('localidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('propietario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['propietario_id'], ['propietario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inmueble')
    op.drop_table('propietario')
    op.drop_table('inquilino')
    # ### end Alembic commands ###
