"""agregar contratos

Revision ID: f7f20cb5f061
Revises: f7127eb1936d
Create Date: 2025-12-06 16:44:12.925132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f7f20cb5f061'
down_revision: Union[str, Sequence[str], None] = 'f7127eb1936d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_fin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('inmueble_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inmueble_id'], ['inmueble.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contrato')
    # ### end Alembic commands ###
